### ISSUE TITLE
A blue screen will appear after using it for a period of time

### ISSUE THREAD

**Issue by Zhaodaidai** [ZeroMemoryEx/Chaos-Rootkit#12]
I use the GUI interface program to hide the process, and then it will blue screen after about an hour or two
![9fc638195df07afb0ef47d4a27637683](https://github.com/ZeroMemoryEx/Chaos-Rootkit/assets/71388480/3ad58b49-b95c-4c4f-9488-effbd5ec684f)
![image](https://github.com/ZeroMemoryEx/Chaos-Rootkit/assets/71388480/779faaa6-2e4b-4cff-8fe7-0e09936f1f94)

**Comment by ZeroMemoryEx** [comment]
Hello @Zhaodaidai , I've already flagged the GUI version as **unstable**. This issue will be completely fixed in the next update. Thank you for bringing it to my attention

**Comment by Zhaodaidai** [comment]
Thank you very much for your notification, I will look forward to the next update!

**Comment by ZeroMemoryEx** [comment]
@Zhaodaidai you can try the last update

**Comment by wisdeth14** [comment]
Hi @ZeroMemoryEx, using your most recent version I experience the same issue. It will run for 30min give or take, and then crash with a blue screen. Event Viewer shows it was a Bugcheck 0x109 (CRITICAL_STRUCTURE_CORRUPTION).

I've attached my debug output from WinDbg: 
[windbg.txt](https://github.com/user-attachments/files/17742199/windbg.txt)
