### ISSUE TITLE
BSOD / Console bug

### ISSUE THREAD

**Issue by Peskedor** [ZeroMemoryEx/Chaos-Rootkit#14]
After hiding a process the OS BSODs after some time - already reported by another users.

Also the console version does have a code mistake in it, its using PROTECTION_LEVEL_ANTIMALWARE_LIGHT instead of HIDE_PROC

**Comment by ZeroMemoryEx** [comment]
I just solved the hiding process, but I still haven't fixed the BSOD. I haven't found the time to solve it yet
