### ISSUE TITLE
Hide registry 

### ISSUE THREAD

**Issue by crack00r** [ZeroMemoryEx/Chaos-Rootkit#16]
Hi, is it possible to hide registry entry’s as well?
I use a tool named reWASD to map controller buttons for call of duty, but it’s anticheat detect it as hack, wich is not, so I look for rootkit to hide reWASD completely in driver, processes and registry… 
Cause cod dont even start if the tool is installed, even if its not running

**Comment by ZeroMemoryEx** [comment]
Hello @crack00r , No, there is currently no feature to hide registry keys in it. However, you might find another rootkit that can accomplish this. It's important to note that the effectiveness of such methods varies depending on the anti-cheat, there's no magic solution to bypass them all.
