### ISSUE TITLE
unable to connect to rootkit INVALID_HANDLE_VALUE

### ISSUE THREAD

**Issue by leanclean** [ZeroMemoryEx/Chaos-Rootkit#17]
https://github.com/ZeroMemoryEx/Chaos-Rootkit/assets/79753082/d029ec2a-df5d-49e2-b268-6894691b4e8a

**Comment by SecretUser112** [comment]
Did you connect the rootkit by using SC service manager before using the GUI to send the request?

**Comment by leanclean** [comment]
how do I do that

**Comment by leanclean** [comment]
Im on the services app but how would I connect to the rootkit

**Comment by leanclean** [comment]
nvm i fixed it by

**Comment by leanclean** [comment]
I fixed this issue by download DSE patcher

**Comment by ZeroMemoryEx** [comment]
Hello @leanclean , did you Disable Driver Signature Enforcement first before loading the rootkit ?

**Comment by ZeroMemoryEx** [comment]
Hi @leanclean, do you have any feedback? Your input is welcome to improve it .

**Comment by ZeroMemoryEx** [comment]
also if you have any feedback about it? Your input is welcome to improve it.

**Comment by leanclean** [comment]
> Hello @leanclean , did you Disable Driver Signature Enforcement first before loading the rootkit ?

yeah it works now

**Comment by leanclean** [comment]
> also if you have any feedback about it? Your input is welcome to improve it.

possibly like add a feature to block an app's permission to check proccess and windows this will be quite useful for user-mode anti-cheats such as Byfron
