### ISSUE TITLE
Errors when trying to compile .sln

### ISSUE THREAD

**Issue by ahabx64** [ZeroMemoryEx/Chaos-Rootkit#18]
When trying to compile the projects .sln with VS it outputs a bunch of warnings which due to compilerflag /WX become an error and doesn't compile. Even after disabling that flag it errors with "Unresolved external symbol FltGetRequestorProcessID" yet when I add fltMgr.lib it errors with MSB4018. I'd love some help with what exactly I'm doing wrong and how I can compile this myself.

**Comment by ZeroMemoryEx** [comment]
Hello @ahabx64 , sorry for the late reply. To fix this issue, go to Settings, then Linker, then Input, and add FltMgr.lib;%(AdditionalDependencies) to the Additional Dependencies input.
