### ISSUE TITLE
Unable to connect to rootkit INVALID_HANDLE_VALUE

### ISSUE THREAD

**Issue by ozohhub** [ZeroMemoryEx/Chaos-Rootkit#20]
I disabled DSE and even tried on test mode but can't load the driver.
How can i fix this?
@ZeroMemoryEx

**Comment by ZeroMemoryEx** [comment]
Hello @ozohhub ,the rootkit currently works only when DSE is disabled, You can disable DSE by opening cmd as an administrator and running the following command:

bcdedit /set testsigning on 

Happy hacking!

**Comment by ozohhub** [comment]
I tried testsigning on but still can’t load the driver. Is there a specific way to load the driver? (Like command: sc create asdf) I also tried installing the driver with the inf file from this repo but didn’t work.
@ZeroMemoryEx

**Comment by ZeroMemoryEx** [comment]
@ozohhub  Did you place the driver chaos-rootkit.sys in the same directory as rin3-gui.exe? Also, can you run [DbgView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), then run the rootkit and send a screenshot of the output in DbgView?

**Comment by ZeroMemoryEx** [comment]
also you should run the ring3-gui.exe as an administrator @ozohhub

**Comment by ozohhub** [comment]
@ZeroMemoryEx sorry for the delay. 
![12345](https://github.com/user-attachments/assets/552e555d-c8d3-4956-8c46-dcf37824f903)

**Comment by ZeroMemoryEx** [comment]
hello @ozohhub did you enable test signing mode ?

**Comment by ZeroMemoryEx** [comment]
From what I can see in DebugView, the driver didn't load

**Comment by ozohhub** [comment]
@ZeroMemoryEx I also tried on test mode but didn't work.
![1](https://github.com/user-attachments/assets/e09f67ac-7ac5-42f6-b63c-3876b9b15d47)

**Comment by ZeroMemoryEx** [comment]
Hello @ozohhub , that's weird it should work in test mode, can you please run the cmd as an administrator and execute the following commands:
- sc stop Chaos-Rootkit
- sc delete Chaos-Rootkit

After that, try running ring3-gui again. If it still doesn't work, please download the [OSR ](https://www.osronline.com/OsrDown.cfm/osrloaderv30.zip%5Ename=osrloaderv30.zip&id=157)program, unzip it and run it as an administrator then browser and select chaos-rootkit.sys, then press Register Service followed by Start Service.

Once you press Start Service, please send me a screenshot of the output in the pop-up.

**Comment by ozohhub** [comment]
@ZeroMemoryEx It says 'A device attached to the system is not functioning'

![1](https://github.com/user-attachments/assets/fb20ab8b-d41d-4fd5-bab1-30bd1f645b67)

**Comment by ZeroMemoryEx** [comment]
@ozohhub Ah yes, that error occurs because the driver returns STATUS_UNSUCCESSFUL during the offset initialization part. I should be more precise with the error details, haha. Your Windows build is incompatible; the rootkit currently supports the following builds: 17763, 18362, or 19045. You may need to use one of those.

**Comment by ozohhub** [comment]
@ZeroMemoryEx I see. thanks for the help

**Comment by ZeroMemoryEx** [comment]
Hello @ozohhub , I’ve made an update. Now, when your system version is not supported, it won’t restrict you from everything. Instead, it will only limit access to features that require offsets, while allowing access to those that don’t. You can download this update in the [release](https://github.com/ZeroMemoryEx/Chaos-Rootkit/releases/tag/c-rootkit.v2.1). Looking forward to your feedback!

![image](https://github.com/user-attachments/assets/e9f086ee-19b7-4ca1-b6ea-75eff273b7ab)
