### ISSUE TITLE
Getting error while trying to hide PID

### ISSUE THREAD

**Issue by pancibuntus** [ZeroMemoryEx/Chaos-Rootkit#21]
![1](https://github.com/user-attachments/assets/a11d7b9c-2a32-4aa6-9dfd-2d94c86ffe36)
![2](https://github.com/user-attachments/assets/10da4915-0bdd-466b-9c7f-bb636ba948eb)

**Comment by ZeroMemoryEx** [comment]
Hello @pancibuntus ,It seems that the rootkit doesn't support your Windows build offsets, which is why it blocked you from using those three features due to the risk of a crash. However, I believe your build is compatible, so I'll be adding it in the next update today. Stay tuned!

**Comment by ZeroMemoryEx** [comment]
@pancibuntus  Can you unload the rootkit and load it again while [DbgView ](https://download.sysinternals.com/files/DebugView.zip) is open with kernel output enabled, so I can verify your Windows build?

To do this, unload the rootkit by running Command Prompt as admin and typing `sc stop chaos-rootkit`. T
hen, run DbgView as admin, enable kernel output

![image](https://github.com/user-attachments/assets/f00631e9-ccae-45a7-b8f9-521e93da1138)

then run ring3-gui, connect to the rootkit, and send me a screenshot of the output in DbgView.

**Comment by ZeroMemoryEx** [comment]
Your version and other versions of Windows 10 and Windows 11 will be supported in the next update (probably by the end of the week) 
A massive update will be pushed, Stay tuned 😎 .

**Comment by ZeroMemoryEx** [comment]
@pancibuntus a question , did you encounter any issues with the other two features, bypassing integrity and file restriction, so I can fix them before pushing any updates?
