### ISSUE TITLE
Loading Driver

### ISSUE THREAD

**Issue by zufukatana** [ZeroMemoryEx/Chaos-Rootkit#23]
Should the driver be loaded as service before running the GUI? tried to load it got untrusted unsigned drivers cannot be loaded blablblalblala as error. Thanks in advance.

**Comment by ZeroMemoryEx** [comment]
Hello @zufukatana , the rootkit currently works only when DSE is disabled, You can disable DSE by opening Command Prompt as an administrator and running the following command:

bcdedit /set testsigning on 

then restart, and it should work. Happy hacking!

**Comment by ZeroMemoryEx** [comment]
@zufukatana  If it worked, could you please leave feedback?
