### ISSUE TITLE
Failed to Open Device

### ISSUE THREAD

**Issue by black-arch7** [ZeroMemoryEx/Chaos-Rootkit#7]
![Screenshot_1](https://github.com/ZeroMemoryEx/Chaos-Rootkit/assets/61597442/e5fc2c85-415e-4965-9137-43c8220718b7)

Please take a look

**Comment by ZeroMemoryEx** [comment]
Hello @black-arch7 , have you loaded the driver first? The app.exe is just an interface to control the rootkit. Try loading the driver first using [OSR](https://www.osronline.com/article.cfm%5Earticle=157.htm), and make sure DSE (Driver Signature Enforcement) is disabled before loading it, Once the driver is loaded, you can start controlling the rootkit with app.exe.

**Comment by black-arch7** [comment]
Thanks for the quick support
