### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gabriel-maxx** [ZeroMemoryEx/Chaos-Rootkit#9]
Hello, I would like to know how do I make it so that when the driver loads automatically it does things for me without needing the usermode interface? for example : look for the process called test.exe elevate to winsystem ppl and then hide it from the task manager ?

**Comment by Hide067** [comment]
The functions are given in the code, you just need to stop being lazy and slow and put them all together and generate the application in the execution order and logic you need!

**Comment by ZeroMemoryEx** [comment]
@Hide067 great answer !!
